# web server
server:
  port: 8080
  servlet:
    context-path: /myapp

# spring
spring:
  application:
    name: hello-validation

# logging
logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
