# web server
server:
  port: 9080
  servlet:
    context-path: /myapp

# spring
spring:
  application:
    name: hello-mybatis
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
    schema: classpath:schema.sql #可以自定义文件名,当有该配置项时,会被auto-configure执行
    data: classpath:data.sql #可以自定义文件名,当有该配置项时,会被auto-configure执行

# logging
logging:
  level:
    root: INFO
    org:
      springframework: INFO

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:/mappers/*.xml
